### ISSUE TITLE
JSON_ARRAY and fast iteration

### ISSUE THREAD

**Issue by egepointr** [vivkin/gason#31]
Hi,

First off - many thanks for such a great library.

when using `for (auto i : obj)` to loop through an array (`JSON_ARRAY`), are we guaranteed for the order? Docs don't seem to specify it so wanted to check.

Many thanks,
Ege

**Comment by vivkin** [comment]
Hi,
Yes order is exactly as items appears in source json document

**Comment by egepointr** [comment]
Thanks @vivkin , we assumed the same. I'd recommend adding it to the documentation.

Have a nice day!
