### ISSUE TITLE
Program terminated with signal SIGSEGV

### ISSUE THREAD

**Issue by y-m-j** [vivkin/gason#38]
Hi,

I have been using the gason tool to flash set of binaries i.e., .FLS files.
In this process using older vjson binary worked absolutely fine, but the latest Gason binaries gave the error as :
Thread 1 "downloadtool" received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
65      ../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.

Thanks in advance for any help on why this error.

**Comment by vivkin** [comment]
Hi, do you have more detailed stacktrace? There is no calls to strlen in gason

**Comment by y-m-j** [comment]
I think issue is in my usage of the right varaibles in gason.h : line 59 
struct JsonNode {
    JsonValue value;
    JsonNode *next;
    char *key;
};

Can you point to these same variables in Vjson release ?
I did a gdb backtrace and got the issue with : key variable.

**Comment by vivkin** [comment]
Maybe you iterating an array? In arrays key feild contains garbage

**Comment by y-m-j** [comment]
I'm porting from the variable I used earlier in Vjson from : value->parent->name
and in Gason to : value->value.toNode()->key

This is causing the issue, so can you help me with what is the appropriate replacement for "name" variable in your code base.

**Comment by vivkin** [comment]
Unfortunately in gason you can't access to node parent. You could track it by hand while iterating

**Comment by y-m-j** [comment]
Thanks, The issue in my case was : 
-- value->value.toNode()->key
++ value->key
